version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: always
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    depends_on:
      - ai-service

  ai-service:
    build: ./ai-service
    ports:
      - "5000:5000"
    volumes:
      - ./ai-service:/app
    restart: always
